sudo: false
language: python
python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7"
cache:
  directories:
    - $HOME/.cache/pip
install:
 - pip install flake8 coverage coveralls "ipaddress; python_version < '3.3'"
script:
  - coverage run check_rbl.py -w99 -c99  -a 8.8.8.8
  - coverage run check_rbl.py -w99 -c99  -a ::ffff:7f00:2
  # - flake8
after_success:
  - coverage report check_rbl.py
  - coveralls
